### ISSUE TITLE
"create new" button is not redirecting to homepage

### ISSUE THREAD

**Issue by sourabhtk37** [sourabhtk37/CodeShare#14]
In `homepage.html` the button should redirect to homepage for creation of new code snippet, but it's just redirecting to the current page.

https://github.com/sourabhtk37/CodeShare/blob/master/code_share/app_code_share/templates/app_code_share/homepage.html#L41

**Comment by sourabhtk37** [comment]
cc: @nishutosh

**Comment by nishutosh** [comment]
k looking into it

**Comment by nishutosh** [comment]
k look i have found the issue i.e never place a button tag inside a <a> tag its not valid in html5 cause its kinda weird clickable inside clickable....here is the link that explains all   https://stackoverflow.com/a/28665849   so you can make a div or something...thats it hope this solves the issue

**Comment by sourabhtk37** [comment]
Great. please don't push directly to master next time.
Closing this issue.
