### ISSUE TITLE
add SSL/TLS

### ISSUE THREAD

**Issue by sourabhtk37** [sourabhtk37/CodeShare#15]
Enable HTTPS connection and redirect all HTTP traffic to HTTPS.

**Comment by sourabhtk37** [comment]
Use let'sencrypt free SSL certificate to have HTTPS connection.
Right now we are having basic security from cloudfare that comes by managing DNS over there.

**Comment by sourabhtk37** [comment]
We can also move from nginx to caddy(caddy does auto HTTPS via let's encrypt)

**Comment by nishutosh** [comment]
my friend has got github pack.. usko use karna nai atta lol usse try marta hu ssl cerificate free from namescheap

**Comment by sourabhtk37** [comment]
Nope, it's not free forever(only for one year, then we have to pay, I too have it)
It's better to use let's encrypt which is free forever.

**Comment by sourabhtk37** [comment]
Fix added for this issue in the branch enhancement-#15

**Comment by sourabhtk37** [comment]
6f36e11 commit fixes #15
