### ISSUE TITLE
No PEP 8 coding standard 

### ISSUE THREAD

**Issue by theparadoxer02** [sourabhtk37/CodeShare#38]
PEP coding standard should be followed.
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/

**Comment by sourabhtk37** [comment]
Could you please update the codebase using any plugin.

**Comment by theparadoxer02** [comment]
Done ! have a look at it @sourabhtk37 
https://github.com/sourabhtk37/CodeShare/pull/39

**Comment by sourabhtk37** [comment]
Fixed by #42
