### ISSUE TITLE
Add copy button for url

### ISSUE THREAD

**Issue by sourabhtk37** [sourabhtk37/CodeShare#41]
Need copy button on hover to directly copy the url.

**Comment by nishutosh** [comment]
@sourabhtk37 should i close this issue or you want a review while master pull?

**Comment by sourabhtk37** [comment]
Wait till it's merged in master. I think that might be a good idea.

**Comment by sourabhtk37** [comment]
Closing issues as it's causing problem by people taking up issues. Apologies. :heart:
