### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by sourabhtk37** [sourabhtk37/CodeShare#8]
Enable syntax highlighting on the client side

**Comment by nishutosh** [comment]
https://ace.c9.io/    this will do i have tested this but there is one problem that we have to specify language before so that we can put the editor in that lang mode ......so we can have a select box for that like hackerrank that asks for lang before using editor

**Comment by sourabhtk37** [comment]
It's not that hard to detect a language. We are not running an online interpreter/compiler etc. So nobody will care to click on the language button. But at least we can guess as to what language the person is using and let him change if he wants.

**Comment by nishutosh** [comment]
and whats the criteria for the guess?

**Comment by sourabhtk37** [comment]
No criteria

**Comment by sourabhtk37** [comment]
Maybe try out [Pygments](http://pygments.org/)
I was thinking if we could have textarea disabled if the user is viewing the snippet so we can have syntax-highlighted snippet there.
Then upon clicking `edit` the textarea is brought back without syntax highlighting.
This also prevent accidental changes from other users trying to view the snippet shared by the author.

What do you think? @nishutosh 
Also check out enhancement-#10 branch for fix I made for #10

**Comment by nishutosh** [comment]
i thinks its better to have syntax highlighting  for editing too .. as it ease the code writing and will force less error while writing.... [http://pygments.org/](url) they too have a select box its better and i think it will do because the problem is we cannot include syntax css for every language else it will take more time to load so we just ask user puts its(language) css to work efficient and fast and we need it have syntax highlight at every end ......if we dont do this we will finally land up in machine learning..lol.. finding patterns in code and guessing the language for the user ..,.we can simply prevent editing by having a simple password to edit the particular file like in password protected pdf the user can share the pass and other can edit it...if no pass then read only  dont worry about page redirections and all we can do this pass checking  by ajax also so...what do you think @sourabhtk37

**Comment by sourabhtk37** [comment]
>as it ease the code writing and will force less error while writing.

are we making an editor? We certainly can have ability to run the program if you want.

>.if we dont do this we will finally land up in machine learning

Har chiz mein ML. Why? Most syntax highlighter libraries already do have ability to identify language. We can simply send ajax on nextline get the language and apply/send css but I am still confused on how to apply css on active textarea.

>we can simply prevent editing by having a simple password to edit the particular file like in password protected pdf the user can share the pass and other can edit it

Definitely NO.
I was talking about in case a user wants to just view the snippet (ofcourse he can edit by clicking edit, which will active textarea) because the author shared in the first place to be viewed by others(we don't yet have real time collaboration). No need for ajax in this case, just a js function.

**Comment by nishutosh** [comment]
> I was talking about in case a user wants to just view the snippet
i
think we should have a mech to stop useless edit imagine i made a code and i shared it someone and he/she just deleted my code then what i will make another file.. if i got a pass i can give pass to person that i trush k he/she will edit for good

**Comment by nishutosh** [comment]
oh this markdown thing sucks ......well leave i was thinking we should have a password for a file so one can delete my code unless i dont wanted it to be changed by someone ....what if someone  deleted my whole code?

**Comment by sourabhtk37** [comment]
For that we can generate two kinds of links:
- editable
- read-only

The editable link remains with the user (once we implement session based auth or full auth)

**Comment by nishutosh** [comment]
no ux will be bad for this no one wants two links for one file..its kinda weird its better that our backend takes care for non usefull edits what do you think @sourabhtk37

**Comment by sourabhtk37** [comment]
Ok, so we create one link after we give choice to user whether they want editable link or read only link.
Like every other cloud storage provider like dropbox or g-drive.

**Comment by nishutosh** [comment]
k this can work but any  good reason for taking link approach rather then password?

**Comment by sourabhtk37** [comment]
managing a password for each file gets hectic(you have to share it to them, they have to remember it too), whereas a link (editable one) can be just opened without remembering additional password.
Basically reducing a step.

**Comment by nishutosh** [comment]
> We certainly can have ability to run the program if you want.

can we have this ? i mean using an online compiler api like hackerearth v2 api

> Most syntax highlighter libraries already do have ability to identify language.

i mean how can they?there are tons of lang out there....this works on textarea **rather than pre tags** checkout this https://ace.c9.io/tool/mode_creator.html

> but I am still confused on how to apply css on active textarea

no big deal...





`

**Comment by sourabhtk37** [comment]
We surely can have this. The performance will decrease that's all.

As I said before we can simply send ajax on next line(enter) get the language and apply/send css.
It is not text area. That are individual spans whose content gets edited by Javascript  and that's why syntax highlighted. Can't happen on text area. If using an editor we can do that.

**Comment by nishutosh** [comment]
Please go for dark theme editor as they are cooler than lighter theme.

**Comment by sourabhtk37** [comment]
Fix for this issue in #45.

**Comment by sourabhtk37** [comment]
Closing this as fix added in `development`
